export const SIGNIN_USER = 'users/SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'users/SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAIL = 'users/SIGNIN_USER_FAIL';
export const SIGNUP_USER = 'users/SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_SUCCESS = 'users/SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'users/SIGNUP_USER_FAIL';
export const SIGNOUT_USER = 'users/SIGNOUT_USER_SUCCESS';
export const SIGNOUT_USER_SUCCESS = 'users/SIGNOUT_USER_SUCCESS';
export const SIGNOUT_USER_FAIL = 'users/SIGNOUT_USER_FAIL';
export const TOGGLE_REMEMBER_PASSWORD = 'TOGGLE_REMEMBER_PASSWORD';
export const UPDATE_USER = 'UPDATE_USER';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CLEAN_SUCCESS_USER = 'CLEAN_SUCCESS_USER';
export const CLEAN_ERROR_USER = 'CLEAN_ERROR_USER';
export const UPDATE_DEPENDENTS_LIST = 'UPDATE_DEPENDENTS_LIST';
export const SELECT_USER_DEPENDENT = 'SELECT_USER_DEPENDENT';
export const RECORD_USER_HOLDER = 'RECORD_USER_HOLDER';

export const CONFIRM_CARD_FAIL = 'CONFIRM_CARD_FAIL';

export const CLEAR_ERROR_PROFILE = 'CLEAR_ERROR_PROFILE';
export const CLEAR_SUCCESS_PROFILE = 'CLEAR_SUCCESS_PROFILE';

export const CARD_CONFIRM_SUCCESS = 'CARD_CONFIRM_SUCCESS';
export const CARD_CONFIRM_FAIL = 'CARD_CONFIRM_FAIL';

export const TERM_LIST_SUCCESS = 'TERM_LIST_SUCCESS';
export const TERM_LIST_FAIL = 'TERM_LIST_FAIL';

export const INTEGRATED_LOCAL_LIST_SUCCESS = 'INTEGRATED_LOCAL_LIST_SUCCESS';
export const INTEGRATED_LOCAL_LIST_FAIL = 'INTEGRATED_LOCAL_LIST_FAIL';

export const HISTORIC_LIST_SUCCESS = 'HISTORIC_LIST_SUCCESS';
export const HISTORIC_LIST_FAIL = 'HISTORIC_LIST_FAIL';

export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const CONFIRM_QUESTION = 'CONFIRM_QUESTION';
export const SELECT_OPTION = 'SELECT_OPTION';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
export const CHECK_QUESTIONS = 'CHECK_QUESTIONS';
export const CHECK_QUESTIONS_FAILED = 'CHECK_QUESTIONS_FAILED';

export const LIST_APPOINTMENTS_SUCCESS = 'LIST_APPOINTMENTS_SUCCESS';
export const LIST_APPOINTMENTS_FAIL = 'LIST_APPOINTMENTS_FAIL';
export const UPDATE_APPOINTMENTS = 'UPDATE_APPOINTMENTS';
export const SEARCH_APPOINTMENT = 'SEARCH_APPOINTMENT';
export const SET_ALL_APPOINTMENT_VISIBLE = 'SET_ALL_APPOINTMENT_VISIBLE';

export const DETAIL_APPOINTMENT_SUCCESS = 'DETAIL_APPOINTMENT_SUCCESS';
export const DETAIL_APPOINTMENT_FAIL = 'DETAIL_APPOINTMENT_FAIL';
export const DETAIL_APPOINTMENT_GET = 'DETAIL_APPOINTMENT_GET';

export const APPOINTMENT_PHYSICAL_CHANGE_VISIBILITY = 'APPOINTMENT_PHYSICAL_CHANGE_VISIBILITY';
export const APPOINTMENT_EXAM_CHANGE_VISIBILITY = 'APPOINTMENT_EXAM_CHANGE_VISIBILITY';
export const APPOINTMENT_EXAM_DETAIL_CHANGE_VISIBILITY = 'APPOINTMENT_EXAM_DETAIL_CHANGE_VISIBILITY';
export const APPOINTMENT_PRESCRIPTION_CHANGE_VISIBILITY = 'APPOINTMENT_PRESCRIPTION_CHANGE_VISIBILITY';

export const LIST_EXAMS_SUCCESS = 'LIST_EXAMS_SUCCESS';
export const LIST_EXAMS_FAIL = 'LIST_EXAMS_FAIL';
export const DETAIL_EXAM_SUCCESS = 'DETAIL_EXAM_SUCCESS';
export const DETAIL_EXAM_FAIL = 'DETAIL_EXAM_FAIL';
export const DETAIL_EXAM_PDF_FAIL = 'DETAIL_EXAM_PDF_FAIL';
export const CLEAR_PDF_ERROR = 'CLEAR_PDF_ERROR';
export const SEARCH_EXAM = 'SEARCH_EXAM';
export const SET_ALL_EXAM_VISIBLE = 'SET_ALL_EXAM_VISIBLE';
export const EXAM_DETAIL_CHANGE_VISIBILITY = 'EXAM_DETAIL_CHANGE_VISIBILITY';

export const LIST_PRESCRIPTIONS_SUCCESS = 'LIST_PRESCRIPTIONS_SUCCESS';
export const LIST_PRESCRIPTIONS_FAIL = 'LIST_PRESCRIPTIONS_FAIL';
export const DETAIL_PRESCRIPTION_SUCCESS = 'DETAIL_PRESCRIPTION_SUCCESS';
export const DETAIL_PRESCRIPTION_FAIL = 'DETAIL_PRESCRIPTION_FAIL';
export const SEARCH_PRESCRIPTION = 'SEARCH_PRESCRIPTION';
export const SET_ALL_PRESCRIPTION_VISIBLE = 'SET_ALL_PRESCRIPTION_VISIBLE';

export const PROFILE_LIST_SUCCESS = 'PROFILE_LIST_SUCCESS';
export const PROFILE_LIST_FAIL = 'PROFILE_LIST_FAIL';

export const PROFILE_UPDATE_HEIGHT_SUCESS = 'PROFILE_UPDATE_HEIGHT_SUCESS';
export const PROFILE_UPDATE_HEIGHT_FAIL = 'PROFILE_UPDATE_HEIGHT_FAIL';

export const PROFILE_UPDATE_WEIGHT_SUCESS = 'PROFILE_UPDATE_WEIGHT_SUCESS';
export const PROFILE_UPDATE_WEIGHT_FAIL = 'PROFILE_UPDATE_WEIGHT_FAIL';

export const PROFILE_UPDATE_IMC_SUCESS = 'PROFILE_UPDATE_IMC_SUCESS';
export const PROFILE_UPDATE_IMC_FAIL = 'PROFILE_UPDATE_IMC_FAIL';

export const PROFILE_UPDATE_GLYCEMIA_SUCCESS = 'PROFILE_UPDATE_GLYCEMIA_SUCCESS';
export const PROFILE_UPDATE_GLYCEMIA_FAIL = 'PROFILE_UPDATE_GLYCEMIA_FAIL';

export const PROFILE_UPDATE_BLOOD_PRESSURE_SUCCESS = 'PROFILE_UPDATE_BLOOD_PRESSURE_SUCCESS';
export const PROFILE_UPDATE_BLOOD_PRESSURE_FAIL = 'PROFILE_UPDATE_BLOOD_PRESSURE_FAIL';

export const PROFILE_ALLERGIES_LIST_SUCCESS = 'PROFILE_ALLERGIES_LIST_SUCCESS';
export const PROFILE_ALLERGIES_LIST_FAIL = 'PROFILE_ALLERGIES_LIST_FAIL';

export const PROFILE_UPDATE_HEART_BEAT_SUCCESS = 'PROFILE_UPDATE_HEART_BEAT_SUCCESS';
export const PROFILE_UPDATE_HEART_BEAT_FAIL = 'PROFILE_UPDATE_HEART_BEAT_FAIL';

export const PROFILE_UPDATE_TEMPERATURE_SUCCESS = 'PROFILE_UPDATE_TEMPERATURE_SUCCESS';
export const PROFILE_UPDATE_TEMPERATURE_FAIL = 'PROFILE_UPDATE_TEMPERATURE_FAIL';

export const PROFILE_PICTURE_SEND_SUCCESS = 'PROFILE_PICTURE_SEND_SUCCESS';
export const PROFILE_PICTURE_SEND_FAIL = 'PROFILE_PICTURE_SEND_FAIL';
export const PROFILE_PICTURE_UPDATE = 'PROFILE_PICTURE_UPDATE';

export const PROFILE_CHANGE_SELECTOR_VISIBILITY = 'PROFILE_CHANGE_SELECTOR_VISIBILITY';
export const PROFILE_SET_HOLDER_USER = 'PROFILE_SET_HOLDER_USER';

export const CLEAR_ERROR_ALLERGIES = 'CLEAR_ERROR_ALLERGIES';
export const CLEAR_SUCCESS_ALLERGIES = 'CLEAR_SUCCESS_ALLERGIES';

export const RESET_ALLERGIES = 'RESET_ALLERGIES';

export const ADVANCE_YEAR_CALENDAR = 'ADVANCE_YEAR_CALENDAR';
export const BACK_YEAR_CALENDAR = 'BACK_YEAR_CALENDAR';
export const FETCH_INDICATORS_SUCCESS = 'FETCH_INDICATORS_SUCCESS';
export const FETCH_INDICATORS_FAIL = 'FETCH_INDICATORS_FAIL';
export const FETCH_INDICATORS_DATA_SUCCESS = 'FETCH_INDICATORS_DATA_SUCCESS';
export const FETCH_INDICATORS_DATA_FAIL = 'FETCH_INDICATORS_DATA_FAIL';
export const CHANGE_YEAR_INDEX = 'CHANGE_YEAR_INDEX';
export const CHANGE_CALENDAR_TYPE = 'CHANGE_CALENDAR_TYPE';
export const TOGGLE_INDICATOR = 'TOGGLE_INDICATOR';
export const CLOSE_INDICATORS_MODAL = 'CLOSE_INDICATORS_MODAL';
export const OPEN_INDICATORS_MODAL = 'OPEN_INDICATORS_MODAL';
export const MIRROR_APP_INDICATORS_SELECTION = 'MIRROR_APP_INDICATORS_SELECTION';
export const MIRROR_SERVER_INDICATORS_SELECTION = 'MIRROR_SERVER_INDICATORS_SELECTION';

export const ADVANCE_MONTH_CALENDAR = 'ADVANCE_MONTH_CALENDAR';
export const BACK_MONTH_CALENDAR = 'BACK_MONTH_CALENDAR';
export const CHANGE_MONTH_INDEX = 'CHANGE_MONTH_INDEX';

export const ADVANCE_DAY_CALENDAR = 'ADVANCE_DAY_CALENDAR';
export const BACK_DAY_CALENDAR = 'BACK_DAY_CALENDAR';
export const CHANGE_DAY_INDEX = 'CHANGE_DAY_INDEX';

export const RESET_YEAR_CALENDAR = 'RESET_YEAR_CALENDAR';
export const RESET_MONTH_CALENDAR = 'RESET_MONTH_CALENDAR';
export const RESET_DAY_CALENDAR = 'RESET_DAY_CALENDAR';

export const REDIRECT_FROM_INDICATOR_DETAIL = 'REDIRECT_FROM_INDICATOR_DETAIL';
export const RESET_INICIO_REDIRECTION = 'RESET_INICIO_REDIRECTION';
export const REDIRECT_FROM_INTEGRATED_LOCALS = 'REDIRECT_FROM_INTEGRATED_LOCALS';
export const REDIRECT_TO_INTEGRATED_LOCALS = 'REDIRECT_FROM_INTEGRATED_LOCALS';
export const REDIRECT_TO_INDICATOR_DETAILS = 'REDIRECT_TO_INDICATOR_DETAILS';

export const CLEAN_ERROR_MESSAGE = 'CLEAN_ERROR_MESSAGE';

export const RESET_TELA_INICIO = 'RESET_TELA_INICIO';
export const RESET_EXAMS = 'RESET_EXAMS';
export const RESET_APPOINTMENTS = 'RESET_APPOINTMENTS';
export const RESET_PRESCRIPTIONS = 'RESET_PRESCRIPTIONS';
export const RESET_PROFILE = 'RESET_PROFILE';

export const RESET_CHRONIC_DISEASES_LIST = 'RESET_CHRONIC_DISEASES_LIST';
export const DELETE_CHRONIC_DISEASE = 'DELETE_CHRONIC_DISEASE';
export const DELETE_CHRONIC_DISEASE_SUCCESS = 'DELETE_CHRONIC_DISEASE_SUCCESS';
export const DELETE_CHRONIC_DISEASE_FAIL = 'DELETE_CHRONIC_DISEASE_FAIL';
export const CHRONIC_DISEASES_LIST_SUCCESS = 'CHRONIC_DISEASES_LIST_SUCCESS';
export const CHRONIC_DISEASES_LIST_FAIL = 'CHRONIC_DISEASES_LIST_FAIL';
export const CHRONIC_DISEASE_UPDATE_CURRENT_INDEX = 'CHRONIC_DISEASE_UPDATE_CURRENT_INDEX';
export const CHRONIC_DISEASE_CLEAN_FORM = 'CHRONIC_DISEASE_CLEAN_FORM';
export const CLEAR_ERROR_CHRONIC_DISEASES = 'CLEAR_ERROR_CHRONIC_DISEASES';
export const SELECT_CHRONIC_DISEASE = 'SELECT_CHRONIC_DISEASE'
export const EDIT_CHRONIC_DISEASE_SUCCESS = 'EDIT_CHRONIC_DISEASE_SUCCESS'
export const EDIT_CHRONIC_DISEASE_FAIL = 'EDIT_CHRONIC_DISEASE_FAIL'
export const INSERT_CHRONIC_DISEASE_SUCCESS = 'INSERT_CHRONIC_DISEASE_SUCCESS'
export const INSERT_CHRONIC_DISEASE_FAIL = 'INSERT_CHRONIC_DISEASE_FAIL'

export const RESET_MEDICINES_LIST = 'RESET_MEDICINES_LIST';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';
export const DELETE_MEDICINE_SUCCESS = 'DELETE_MEDICINE_SUCCESS';
export const MEDICINES_LIST_SUCCESS = 'MEDICINES_LIST_SUCCESS';
export const MEDICINES_LIST_FAIL = 'MEDICINES_LIST_FAIL';
export const MEDICINE_UPDATE_CURRENT_INDEX = 'MEDICINE_UPDATE_CURRENT_INDEX';
export const MEDICINE_CLEAN_FORM = 'MEDICINE_CLEAN_FORM';
export const MEDICINE_REMOVE_FROM_REDUCER = 'MEDICINE_REMOVE_FROM_REDUCER';

export const CLEAR_ERROR_MEDICINES = 'CLEAR_ERROR_MEDICINES';

export const INICIO_CALENDAR_TYPE_YEAR = 'INICIO_CALENDAR_TYPE_YEAR';
export const INICIO_CALENDAR_TYPE_MONTH = 'INICIO_CALENDAR_TYPE_MONTH';
export const INICIO_CALENDAR_TYPE_DAY = 'INICIO_CALENDAR_TYPE_DAY';

export const INICIO_SELECT_CALENDAR_TYPE = 'INICIO_SELECT_CALENDAR_TYPE';
export const INICIO_GET_CALENDAR_TYPE = 'INICIO_GET_CALENDAR_TYPE';
export const INICIO_SET_CALENDAR_VALUE = 'INICIO_SET_CALENDAR_VALUE';
export const INICIO_SET_CALENDAR_NUMBER_VALUE = 'INICIO_SET_CALENDAR_NUMBER_VALUE';

export const INICIO_RESET = 'INICIO_RESET';

export const INDICATORS_GET_SUCCESS = 'INDICATORS_GET_SUCCESS';
export const INDICATORS_GET_FAIL = 'INDICATORS_GET_FAIL';
export const INDICATORS_SELECT = 'INDICATORS_SELECT';
export const INDICATORS_SHOW_MODAL = 'INDICATORS_SHOW_MODAL';
export const INDICATORS_HIDE_MODAL = 'INDICATORS_HIDE_MODAL';
export const INDICATORS_ADD_OR_REMOVE = 'INDICATORS_ADD_OR_REMOVE';
export const INDICATORS_GET_DATA_SUCCESS = 'INDICATORS_GET_DATA_SUCCESS';
export const INDICATORS_GET_DATA_FAIL = 'INDICATORS_GET_DATA_FAIL';
export const INDICATORS_CLEAN_DATA_FAIL = 'INDICATORS_CLEAN_DATA_FAIL';
export const INDICATORS_UPDATE_SELECTED_SUCCESS = 'INDICATORS_UPDATE_SELECTED_SUCCESS';
export const RESET_INDICATORS = 'RESET_INDICATORS';

export const NOTIFICATION_ADD_MANY = 'NOTIFICATION_ADD_MANY';
export const NOTIFICATION_ADD_LOCAL = 'NOTIFICATION_ADD_LOCAL';
export const NOTIFICATION_SCHEDULE_LOCAL = 'NOTIFICATION_SCHEDULE_LOCAL';
export const NOTIFICATION_DELETE_LOCAL = 'NOTIFICATION_DELETE_LOCAL';
export const NOTIFICATION_CHECK_FIRED_LOCAL = 'NOTIFICATION_CHECK_FIRED_LOCAL';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';
export const NOTIFICATION_RESET_LIST = 'NOTIFICATION_RESET_LIST';
export const NOTIFICATION_SET_COUNTER = 'NOTIFICATION_SET_COUNTER';
export const NOTIFICATION_ADD_REMOTE = 'NOTIFICATION_ADD_REMOTE';
export const NOTIFICATION_UPDATE_LAST_REQUEST = 'NOTIFICATION_UPDATE_LAST_REQUEST';
export const NOTIFICATION_CLEAR_ADD_MANY = 'NOTIFICATION_CLEAR_ADD_MANY';
export const NOTIFICATION_DELETE_FROM_REDUCER = 'NOTIFICATION_DELETE_FROM_REDUCER';

export const FORGOT_PASSWORD_SET_MSG = 'FORGOT_PASSWORD_SET_MSG';
export const FORGOT_PASSWORD_SET_TOKEN = 'FORGOT_PASSWORD_SET_TOKEN';
export const FORGOT_PASSWORD_FAIL_MSG = 'FORGOT_PASSWORD_FAIL_MSG';
export const FORGOT_PASSWORD_SUCCESS_MSG = 'FORGOT_PASSWORD_SUCCESS_MSG';
export const FORGOT_PASSWORD_CLEAR_FAIL_MSG = 'FORGOT_PASSWORD_CLEAR_FAIL_MSG';
export const FORGOT_PASSWORD_CLEAR_SUCCESS_MSG = 'FORGOT_PASSWORD_CLEAR_SUCCESS_MSG';

export const SETTINGS_SET_INDICATOR = 'SETTINGS_SET_INDICATOR';
export const SETTINGS_UPDATE_INDICATOR = 'SETTINGS_UPDATE_INDICATOR';
export const SETTINGS_SET_INDICATOR_DATA = 'SETTINGS_SET_INDICATOR_DATA';
export const SETTINGS_UPDATE_INDICATOR_DATA = 'SETTINGS_UPDATE_INDICATOR_DATA';
export const SETTINGS_SET_APPOINTMENT = 'SETTINGS_SET_APPOINTMENT';
export const SETTINGS_UPDATE_APPOINTMENT = 'SETTINGS_UPDATE_APPOINTMENT';
export const SETTINGS_SET_EXAM = 'SETTINGS_SET_EXAM';
export const SETTINGS_UPDATE_EXAM = 'SETTINGS_UPDATE_EXAM';
export const SETTINGS_SET_PRESCRIPTION = 'SETTINGS_SET_PRESCRIPTION';
export const SETTINGS_UPDATE_PRESCRIPTION = 'SETTINGS_UPDATE_PRESCRIPTION';
export const SETTINGS_SET_ALLERGIE = 'SETTINGS_SET_ALLERGIE';
export const SETTINGS_UPDATE_ALLERGIE = 'SETTINGS_UPDATE_ALLERGIE';
export const SETTINGS_CLEAN = 'SETTINGS_CLEAN';

export const START_LOADING = 'START_LOADING';
export const START_LOADING_APPOINTMENT = 'START_LOADING_APPOINTMENT';
export const START_LOADING_EXAM = 'START_LOADING_EXAM';
export const START_LOADING_PRESCRIPTION = 'START_LOADING_PRESCRIPTION';
export const START_LOADING_INDICATOR = 'START_LOADING_INDICATOR';

export const STOP_LOADING = 'STOP_LOADING';
export const STOP_LOADING_APPOINTMENT = 'STOP_LOADING_APPOINTMENT';
export const STOP_LOADING_EXAM = 'STOP_LOADING_EXAM';
export const STOP_LOADING_PRESCRIPTION = 'STOP_LOADING_PRESCRIPTION';
export const STOP_LOADING_INDICATOR = 'STOP_LOADING_INDICATOR';

export const DOCTOR_AUTH_ADD = 'DOCTOR_AUTH_ADD';
export const DOCTOR_AUTH_ERROR = 'DOCTOR_AUTH_ERROR';
export const DOCTOR_AUTH_RESET = 'DOCTOR_AUTH_RESET';
export const DOCTOR_AUTH_SET_QR_CODE = 'DOCTOR_AUTH_SET_QR_CODE';
export const DOCTOR_AUTH_MODAL_VISIBLE = 'DOCTOR_AUTH_MODAL_VISIBLE';


export const CALENDAR_TYPE = {
  year: 'year',
  month: 'month',
  day: 'day',
};
