# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ffit_curso' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ffit_curso

  pod 'FLAnimatedImage'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
